### ISSUE TITLE
Add a description for the repo

### ISSUE THREAD

**Issue by krishguptadev** [AnishDe12020/AnishDe12020#8]
![image](https://user-images.githubusercontent.com/91655303/143874489-ecaa1c72-f89c-4fd6-bf31-12c4793c7b1b.png)

could be like:

![image](https://user-images.githubusercontent.com/91655303/143874571-64aebec9-caec-4021-8049-1fef0fe04cfb.png)

also add a link and label as in the ss.

**Comment by AnishDe12020** [comment]
Done
